services:
  etl:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - .env
    volumes:
      - ./data:/tmp/data
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=carbon_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: